# Generated by Django 3.0.14 on 2024-02-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Mypost',
        ),
    ]
